AllCops:
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Layout/IndentHash:
  EnforcedStyle: special_inside_parentheses
  SupportedStyles:
    - special_inside_parentheses
    - consistent
    - align_braces
  IndentationWidth: 4

Layout/IndentArray:
  EnforcedStyle: special_inside_parentheses
  SupportedStyles:
    - special_inside_parentheses
    - consistent
    - align_braces
  IndentationWidth: 4

Style/BlockComments:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  SupportedStyles:
    - indented
    - indented_relative_to_receiver
  # By default, the indentation width from Style/IndentationWidth is used
  # But it can be overridden by setting this parameter
  IndentationWidth: 4

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'config/routes.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
