default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'user' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'password' } %>
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  port: 5432

development:
  <<: *default
  database: magmonitor_development

test:
  <<: *default
  database: magmonitor_test

production:
  <<: *default
  database: magmonitor_production
